#!/usr/bin/env bash

TOOLCHAIN=$PWD/android-toolchain
mkdir -p $TOOLCHAIN
android-ndk-r10e/build/tools/make-standalone-toolchain.sh \
    		--toolchain=arm-linux-androideabi-4.8 \
    		--arch=arm \
    		--install-dir=$TOOLCHAIN \
    		--platform=android-21
PATH=$TOOLCHAIN/bin:$PATH
