/* Automatically generated by ./generate-cmdlist.sh */
struct cmdname_help {
    char name[16];
    char help[80];
};

static struct cmdname_help common_cmds[] = {
  {"add", N_("Add file contents to the index")},
  {"bisect", N_("Find by binary search the change that introduced a bug")},
  {"branch", N_("List, create, or delete branches")},
  {"checkout", N_("Checkout a branch or paths to the working tree")},
  {"clone", N_("Clone a repository into a new directory")},
  {"commit", N_("Record changes to the repository")},
  {"diff", N_("Show changes between commits, commit and working tree, etc")},
  {"fetch", N_("Download objects and refs from another repository")},
  {"grep", N_("Print lines matching a pattern")},
  {"init", N_("Create an empty Git repository or reinitialize an existing one")},
  {"log", N_("Show commit logs")},
  {"merge", N_("Join two or more development histories together")},
  {"mv", N_("Move or rename a file, a directory, or a symlink")},
  {"pull", N_("Fetch from and integrate with another repository or a local branch")},
  {"push", N_("Update remote refs along with associated objects")},
  {"rebase", N_("Forward-port local commits to the updated upstream head")},
  {"reset", N_("Reset current HEAD to the specified state")},
  {"rm", N_("Remove files from the working tree and from the index")},
  {"show", N_("Show various types of objects")},
  {"status", N_("Show the working tree status")},
  {"tag", N_("Create, list, delete or verify a tag object signed with GPG")},
};
