#! /bin/sh

TOPSRCDIR=`dirname $0`

PKG=git-2.10.1

: ${TARGET:=/usr/local}
PKGDIR=$TARGET/stow/$PKG

OPTS=''

set -x
(cd $TOPSRCDIR && make configure)
exec $TOPSRCDIR/configure --prefix=$PKGDIR $OPTS ${1+"$@"}
