#!/usr/bin/perl

my %local = (
	map { $_ => 1 }
	map { chomp; $_ }
	`Meta/topics`
);
my %remote = (
	map { $_ => 1 }
	grep { m{/} }
	map { s,^github/,,; $_ }
	map { chomp; $_ }
	`git for-each-ref --format='%(refname:short)' refs/remotes/github`
);

if (grep { $_ eq "--matched" } @ARGV) {
	print "$_\n" foreach grep { $remote{$_} } (sort keys(%local));
	exit 0;
}

my @push = grep { !$remote{$_} } (sort keys(%local));
my @prune = grep { !$local{$_} } (sort keys(%remote));

if (grep { $_ eq "--stale" } @ARGV) {
	print "PUSH:$_\n" foreach @push;
	print "PRUNE:$_\n" foreach @prune;
	exit 0;
}
elsif (grep { $_ eq "--push" } @ARGV) {
	print "$_\n" for @push;
	print ":$_\n" for @prune;
	exit 0;
}

if (@push) {
	print "Local branches that need pushed:\n";
	print $_, "\n" foreach @push;
}
if (@prune) {
	print "\n" if @push;
	print "Remote branches that need pruned:\n";
	print $_, "\n" foreach @prune;
}
