#!/bin/sh

echo "/* Automatically generated by $0 */
struct cmdname_help {
	char name[16];
	char help[80];
	unsigned char group;
};

static const char *common_cmd_groups[] = {"

tmp=cmdgrps$$.tmp
trap "rm -fr $tmp" 0 1 2 3 15

sed -n '
	1,/^### common groups/b
	/^### command list/q
	/^#/d; /^[ 	]*$/b
	h;s/^[^ 	][^ 	]*[ 	][ 	]*\(.*\)/	N_("\1"),/p
	g;s/^\([^ 	][^ 	]*\)[ 	].*/\1/w '$tmp'
	'
printf '};\n\n'

n=0
matchgrp=
substnum=
while read grp
do
	matchgrp="$matchgrp${matchgrp:+
}^git-..*[ 	]$grp"
	substnum="$substnum${substnum:+;}s/[ 	]$grp/$n/"
	n=$(($n+1))
done <$tmp

printf 'static struct cmdname_help common_cmds[] = {\n'
grep "$matchgrp" |
sed 's/^git-//' |
sort |
while read cmd tags
do
	tag=$(echo $tags | sed "$substnum; s/[^0-9]//g")
	sed -n '
		/^NAME/,/git-'"$cmd"'/H
		${
			x
			s/.*git-'"$cmd"' - \(.*\)/	{"'"$cmd"'", N_("\1"), '$tag'},/
			p
		}' "Documentation/git-$cmd.txt"
done
echo "};"
