#!/bin/bash
# Copyright (c) 2012 Felipe Contreras

alias=$1
url=$2

dir="$GIT_DIR/testgit/$alias"
prefix="refs/testgit/$alias"

default_refspec="refs/heads/*:${prefix}/heads/*"

refspec="${GIT_REMOTE_TESTGIT_REFSPEC-$default_refspec}"

gitmarks="$dir/git.marks"
testgitmarks="$dir/testgit.marks"

test -z "$refspec" && prefix="refs"

export GIT_DIR="$url/.git"

mkdir -p "$dir"

if test -z "$GIT_REMOTE_TESTGIT_NO_MARKS"
then
	test -e "$gitmarks" || >"$gitmarks"
	test -e "$testgitmarks" || >"$testgitmarks"
else
	>"$gitmarks"
	>"$testgitmarks"
fi

while read line
do
	case $line in
	capabilities)
		echo 'import'
		echo 'export'
		test -n "$refspec" && echo "refspec $refspec"
		echo "*import-marks $gitmarks"
		echo "*export-marks $gitmarks"
		echo
		;;
	list)
		git for-each-ref --format='? %(refname)' 'refs/heads/'
		head=$(git symbolic-ref HEAD)
		echo "@$head HEAD"
		echo
		;;
	import*)
		# read all import lines
		while true
		do
			ref="${line#* }"
			refs="$refs $ref"
			read line
			test "${line%% *}" != "import" && break
		done

		echo "feature import-marks=$gitmarks"
		echo "feature export-marks=$gitmarks"
		git fast-export --use-done-feature \
		    --{import,export}-marks="$testgitmarks" $refs |
		sed -e "s#refs/heads/#${prefix}/heads/#g"
		;;
	export)
		before=$(git for-each-ref --format='%(refname) %(objectname)')

		git fast-import --{import,export}-marks="$testgitmarks" --quiet

		after=$(git for-each-ref --format='%(refname) %(objectname)')

		# figure out which refs were updated
		join -e 0 -o '0 1.2 2.2' -a 2 <(echo "$before") <(echo "$after") | while read ref a b; do
			test $a == $b && continue
			echo "ok $ref"
		done

		echo
		;;
	'')
		exit
		;;
	esac
done
