#!/usr/bin/env python
import sys
import subprocess

if len(sys.argv) is 1:
    print "Didn't do anything"
s = "git log origin/master..HEAD --format=%H -1 -- {0}".format(sys.argv[1])
print s
prev_commit_hash =  subprocess.check_output(s.split()).strip()

s = "git commit --fixup={0} -- {1}".format(prev_commit_hash, sys.argv[1])
print subprocess.check_output(s.split()).strip()

