#!/bin/sh

show() {
	printf '%25s: %s\n' "$1" "$2"
}

check_merge() {
	if test -z "`git cherry $2 $1 $3 | grep -v ^-`"; then
		show $1 "merged to $2"
		return 0
	fi
	return 1
}

for i in `Meta/topics`; do
	upstream=`git for-each-ref --format='%(upstream)' refs/heads/$i`
	check_merge $i origin/master ${upstream:-origin} ||
	check_merge $i origin/next ${upstream:-origin} ||
	show $i 'not merged'
done
exit 0
