#!/bin/sh

for i in `Meta/topics`; do
	upstream=`git for-each-ref --format='%(upstream)' refs/heads/$i`
	upstream=${upstream:-origin}
	if test -n "`git rev-list -1 "$upstream" ^$i`"; then
		echo "===> Rebasing $i"
		git rebase "$upstream" $i || exit 1
	else
		echo "===> Skipping $i"
	fi
done
