#!/bin/sh

base=origin

for i in `Meta/topics`; do
	if test -n "`git rev-list -1 $base ^$i`"; then
		echo "===> Rebasing $i"
		upstream=`git for-each-ref --format='%(upstream)' refs/heads/$i`
		git rebase "${upstream:-origin}" $i || exit 1
	else
		echo "===> Skipping $i"
	fi
done
