#!/bin/sh

for i in `Meta/topics`; do
	upstream=`git for-each-ref --format='%(upstream)' refs/heads/$i`
	upstream=${upstream:-origin}

	case "$i" in
	*/maint-*)
		echo "===> Skipping $i (maint)"
		continue
		;;
	esac

	if test -z "`git rev-list -1 "$upstream" ^$i`"; then
		echo "===> Skipping $i"
		continue
	fi

	echo "===> Rebasing $i"
	git rebase "$upstream" $i || exit 1
done
