#!/bin/sh

if test -n "`git rev-list -1 private..private@{u}`"; then
	echo MERGE:private
fi

Meta/extra --stale

for i in `Meta/extra --matched`; do
	if test -n "`git rev-list -1 github/$i..$i`"; then
		echo PUSH:all
		break;
	fi
done
