#!/bin/sh

note="`git rev-parse --git-dir`/NOTE_MSG"

sed '1,/^---$/d' <"$1" >"$note.tmp" &&
git stripspace -s <"$note.tmp" >"$note" &&
rm -f "$note.tmp" &&
sed '/^---$/,$d' <"$1" >"$1.tmp" &&
mv "$1.tmp" "$1"
