#!/bin/sh

c=Meta/config

dots() {
	echo "$1" |
	perl -aF/ -ne 'print map { "../" } (1..$#F)'
}

link() {
	dest="`dots $2`$1"
	test "`readlink $2`" = "$dest" ||
	ln -vsfT "$dest" "$2"
}

link $c/exclude .git/info/exclude
link $c/config.mak config.mak
