All filters are by equality
task id: task name: task state: task estimated start date: task estimated end date: task real start date: task real end date: task priority: task type: task estimated time: task real time: - Removing asignations and asociations to task 1 ... 
0 | ruta1
+ Selected unique file
- Deasociated file 'ruta1'
- Task 1 prepared to be removed
- Removing asignations and asociations to task 2 ... 
- Task 2 prepared to be removed
- Removing asignations and asociations to task 3 ... 
- Task 3 prepared to be removed
- Removing asignations and asociations to task 4 ... 
- Task 4 prepared to be removed
- Removing asignations and asociations to task 5 ... 
- Task 5 prepared to be removed
** All selected task removed successfully
