#!/bin/bash

want() {
	git for-each-ref --format='%(refname)' |
	xargs Meta/install/prefix |
	sort
}

comm -23 <(Meta/install/versions) <(want) |
while read cruft; do
	dir=$HOME/local/git/$cruft
	echo >&2 "Removing $dir..."
	rm -rf "$dir"
done
