#!/bin/bash

have() {
	for i in $HOME/local/bin/git.*; do
		echo ${i#$HOME/local/bin/git.}
	done
}

want() {
	Meta/install/versions
}

comm -23 <(have) <(want) |
while read version; do
	rm -vf $HOME/local/bin/git.$version
done

comm -13 <(have) <(want) |
while read version; do
  ln -sfTv ../git/$version/bin/git $HOME/local/bin/git.$version
done

ln -sfTv $PWD/bin-wrappers/git $HOME/local/bin/git.compile
